version: "3.7"

# networks:
#   webnet:
#     driver: overlay
#     attachable: true # Needed in order to run custom commands in the container
services:
  pgadmin_dev:
    image: dpage/pgadmin4
    depends_on:
      - db_dev
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - pgadminDev:/var/lib/pgadmin
  db_dev:
    image: postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdataDev:/var/lib/postgresql/data
    # networks:
    #   - webnet 
  api_dev:
    image: authmanager:0.1.0-dev
    build:
      context: .
      args:
        mix_env: dev
        get_deps: deps.get
    ports:
      - "81:4000"
    env_file:
      - config/docker.env
    environment:
      - DATABASE_HOST=db_dev
      - DATABASE_NAME=authManager_dev
      - DATABASE_EVENTSTORE_NAME=authManager_eventstore_dev
      # - DATABASE_URL=ecto://postgres:postgres@host.docker.internal/authManager_dev
      - PORT=4000
    depends_on:
      - db_dev
    # networks:
    #   - webnet
    restart: on-failure


volumes:
  pgdataDev:
  pgadminDev: