version: "3.7"

# networks:
#   webnet:
#     driver: overlay
#     attachable: true # Needed in order to run custom commands in the container
services:
  pgadmin_prod:
    image: dpage/pgadmin4
    depends_on:
      - db_prod
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - pgadminProd:/var/lib/pgadmin
  db_prod:
    image: postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdataProd:/var/lib/postgresql/data
    # networks:
    #   - webnet 
  api_prod:
    image: authmanager:0.1.0
    build:
      context: .
      args:
        mix_env: prod
        get_deps: "deps.get --only prod"
    ports:
      - "80:4000"
    env_file:
      - config/docker.env
    environment:
      - DATABASE_HOST=db_prod
      - DATABASE_NAME=authManager_prod
      - DATABASE_EVENTSTORE_NAME=authManager_eventstore_dev
      - DATABASE_URL=ecto://postgres:postgres@5.135.149.55/authManager_prod
      - DATABASE_EVENTSTORE_URL=ecto://postgres:postgres@5.135.149.55/authManager_eventstore_dev
      - PORT=4000
    depends_on:
      - db_prod
    # networks:
    #   - webnet
    restart: on-failure


volumes:
  pgdataProd:
  pgadminProd: